# Generated by Django 5.2.17 on 2026-09-30 16:00

from django.db import migrations, models


def populate_order_snapshots_and_pending_status(apps, schema_editor):
    Order = apps.get_model("kitchen", "Order")
    OrderItem = apps.get_model("kitchen", "OrderItem")
    Order.objects.filter(status="new").update(status="pending")
    for item in OrderItem.objects.select_related("food_item", "variant").iterator():
        item.product_name = item.food_item.name
        item.variant_name_snapshot = item.variant.name if item.variant_id else ""
        item.save(update_fields=("product_name", "variant_name_snapshot"))


def restore_new_status(apps, schema_editor):
    Order = apps.get_model("kitchen", "Order")
    Order.objects.filter(status="pending").update(status="new")


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0026_add_plate_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='minimum_quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum number of this item customers must order'),
        ),
        migrations.AddField(
            model_name='foodvariant',
            name='minimum_quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum number of this size customers must order'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='building_society',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flat_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='submission_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name_snapshot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(populate_order_snapshots_and_pending_status, restore_new_status),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 1)), name='kitchen_item_min_quantity_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='foodvariant',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 1)), name='kitchen_variant_min_quantity_gte_one'),
        ),
    ]
