# Generated by Django 5.2.17 on 2026-09-30 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0027_fooditem_minimum_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='minimum_quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum number of this item customers must order', validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='foodvariant',
            name='minimum_quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum number of this size customers must order', validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__lte', 999)), name='kitchen_item_min_quantity_lte_999'),
        ),
        migrations.AddConstraint(
            model_name='foodvariant',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__lte', 999)), name='kitchen_variant_min_quantity_lte_999'),
        ),
    ]
